grafana/grafana-image-renderer

src/browser.ts

When using grafana-image-renderer with [Grafana 6.3.3](https://github.com/grafana/grafana/releases/tag/v6.3.3) I was getting several dashboards that were rendering with empty panels. Upon inspection of the page, I realized that there is not a '.panel' class applied to the panels any more. 
I added `|| document.querySelectorAll('.panel-container').length` to line 73 to account for this change. 
I have not done any rigorous testing, but it did solve my problem.
I am using grafana-image-renderer as a docker image.

Updated the panelCount query in the page.waitForFunction()

---

.dockerignore
Dockerfile
src/browser.ts

Swtich from `node:10` to `node:10-alpine`. 
- Better from a security point. 
- Smaller image 535MB vs 1.66GB
This works on my machine, but the current docker image installs a lot of additional dependencies related to fonts etc so I'm unsure if my suggested changes is enough.

Switch docker base to node:10-alpine

---

Dockerfile

**Before update:**
```bash
> docker run --rm -v $HOME/.cache:/root/.cache/ aquasec/trivy --clear-cache grafana/grafana-image-renderer:latest                                                                                                                             
2019-11-18T22:24:46.663Z        INFO    Removing image caches...                                                                                                                                                                              
2019-11-18T22:24:46.668Z        INFO    Updating vulnerability database...                                                                                                                                                                    
2019-11-18T22:25:04.827Z        INFO    Detecting …
```

Docker: Updates dependencies to remove vulnerabilities

---

Dockerfile

Based on https://github.com/grafana/grafana-image-renderer/pull/53#issuecomment-556344273 cleaning up the Dockerfile. Note: The only way I could properly remove nghttp2 openldap curl packages was to first install them, not sure if there are any easier/better way?

Docker: Fix Dockerfile

---

src/browser.ts

Consider using waitUntil in page.goto to fix empty pngs
Sometimes 'load' event fires before query data is fetched, and page.waitForFunction bit doesn't help with that. This fix uses puppeteer's 'networkidle0' event, which ensures there is no active network requests for 500ms.

Wait until all network connections to be idle before rendering

---

README.md
docs/remote_rendering_using_docker.md
src/browser.ts
src/grpc-plugin.ts
src/http-server.ts
src/logger.ts

Makes it possible to configure puppeteer with `ignoreHttpsErrors` when launching chrome, see https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions. 
Fixes #33

Ignore https errors using environment variable

---

CHANGELOG.md
src/browser.ts
src/grpc-plugin.ts
src/http-server.ts

Provide correctly named config parameter to Chromium when overriding to skip https errors using environment variable `GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS` and/or `IGNORE_HTTPS_ERRORS`.

Provide correctly named config parameter to Chromium when overriding to skip https errors

---

.dockerignore
Dockerfile
default.json
dev.json
package.json
src/app.ts
src/browser.ts
src/config.ts
src/plugin/grpc-plugin.ts
src/service/http-server.ts
yarn.lock

By providing `--config=<json file>` as arg to render service (not plugin) you can now provide config from file. If existing environment variables are used they will be applied after reading in configuration from file.

Remote rendering: Support reading config from file

---

README.md
docs/remote_rendering_using_docker.md
src/app.ts

Renames `TZ` env variables to `GF_RENDERER_PLUGIN_TZ` for plugin and `BROWSER_TZ` for service. Fallbacks to `TZ` env variable.

Rename default timezone env variables

---

README.md
src/app.ts
src/config.ts
src/plugin/grpc-plugin.ts

Changes default grpc port from 50059 to 0 (auto assign).
Add support for env variable GF_RENDERER_PLUGIN_GRPC_PORT
to set configure grpc port.

Plugin: Automatically assign gRPC port per default

---

Dockerfile
debian.Dockerfile
src/logger.ts
src/plugin/grpc-plugin.ts
src/service/http-server.ts
src/service/metrics_middleware.ts

Had completely screwed up the exception handling when running as HTTP service, basically swallowed the exception and tried to log it, but the logger was badly implemented. This is the reason why metrics only showed 200 response statuses and nothing else :)
Changes:
- Service: Don't swallow exceptions and fix logging of parameters
- Metrics: Use status 499 when client close the connection
- When Grafana cancel a render request status 499 is used for
the http_request_duration_seconds_* metrics instead of 200.
499 is a non-standard code and is used by Nginx and I think
it's okay to use this here since the code is not returned
to any client.
- Docker: Set NODE_ENV=production
- not sure this makes any difference, but couldn't hurt
- Changed request logging to use debug level if status < 400 …

Remote rendering: Improve error handling, logging and metrics

---

src/browser/browser.ts

Add a call to the mouse.move function so the mouse is in the bottom right corner of the viewport instead of the top left corner. 
It allows to not have the "mouse:hover" style on titles while rendering panels.
I've tested several calls to the render function and it seems not to have any other impact.
Fixes #111

Render: Fix panel titles should not be focused when rendering

---

README.md
docs/remote_rendering_using_docker.md
src/app.ts

Verbose rendering logging have been possible to enable only thru
configuration file and when running in remote rendering setup. 
This adds support for enabling verbose logging using environment 
variable.

Add support for enabling verbose logging using environment variable

---

src/browser/browser.ts

Give a better error message when trying to render when Grafana is running in socket mode, since this doesn't work with Puppeteer.

Browser: Fail render if the URL has socket protocol

---

CHANGELOG.md
plugin.json

Planning to update documentation later for v2.0.0 stable or beta2 (#130)

Release grafana-image-renderer v2.0.0-beta1

---

package.json
yarn.lock

Upgrade boom to resolve dependabot security alert due to outdated hoek version.

Chore: Upgrade boom to resolve hoek security alert

---

eslint.json
package.json
yarn.lock

Switch from tslint to eslint, since the former is deprecated and advises to switch to the latter.

WIP: Chore: Switch from tslint to eslint

---

src/browser/browser.ts

Fix #169
page.goto timeout needs to be aligned to query timeout in remote server mode.

Use timeout opt value for browser page.goto

---

.circleci/config.yml

Having problems with the release. The version of grabpl used in the CircleCI config ignores images in the manifest. This means it is not possible to publish a new version of the plugin.

circleci: newest version of grabpl

---

.circleci/config.yml

Attempting to apply this fix for the CircleCI build: https://support.circleci.com/hc/en-us/articles/360050934711
The Docker build is failing: https://app.circleci.com/pipelines/github/grafana/grafana-image-renderer/243/workflows/49ad3267-49ca-42f7-94b0-c91ed2ed05c8/jobs/732
with this error:
```
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/usr/local/share/.cache/yarn/v6/npm-core-util-is-1.0.2-b5fd54220aa2bc5ab57aab7140c940754503c1a7-integrity/node_modules/core-util-is/LICENSE' -> '/usr/src/app/node_modules/core-util-is/LICENSE'".
```

circleci: upgrade docker

---

.circleci/config.yml
Dockerfile
debian.Dockerfile
docs/remote_rendering_using_docker.md
package.json
scripts/pkg.js
src/service/http-server.ts
yarn.lock

This PR upgrades some dependencies, the upgrade is always the minimum necessary to get rid of vulnerabilities on these dependencies (or sub-dependencies). I also ran `yarn upgrade` to upgrade all dependencies and sub-dependencies.
This PR is based on this one for the Node bump: https://github.com/grafana/grafana-image-renderer/pull/214
Mainly tested on Windows (to build and run the packaged version), built the package successfully on Linux too.

Chore: Upgrade dependencies and bump Node to LTS

---

package.json
proto/rendererv2.proto
src/browser/browser.ts
src/browser/clustered.ts
src/browser/reusable.ts
src/plugin/v1/grpc_plugin.ts
src/plugin/v2/grpc_plugin.ts
src/plugin/v2/types.ts
src/service/http-server.ts
yarn.lock

Extend the existing `render` function to be able to render panels as CSVs and not PNGs.
Plus, extend the `RenderResponse` to be able to return a file name, used to have access to the original download file name. 
**Open questions:**
- I'm not sure if the `yarn.lock` file contains the right information as I did a lot of tests and may have pushed some wrong content. How can I clean it up? 
- I'm not sure about extending the existing `render` function or make a new one. There is a lot in common between the CSV rendering and the PNG rendering.

Add CSV export feature

---

src/browser/browser.ts

Rename can’t be used to rename across devices so this PR replaces `renameSync` with `copyFileSync` and `unlinkSync`.

CSV: replace rename file with copy and unlink

---

yarn.lock

Bumps path-parse from 1.0.6 to 1.0.7

Chore: Bump path-parse from 1.0.6 to 1.0.7

---

src/service/http-server.ts

Add an endpoint for the HTTP Server mode to know the current version of the plugin that is running.
*Note: I'd prefer to have the path `/version` for the endpoint instead of `/render/version` but it's harder to handle on the Grafana side as the config field for the `rendererUrl` contains the `/render` endpoint.*

HTTP Server: add version endpoint to get the current version

---

.circleci/config.yml

Follow-up of https://github.com/grafana/grafana-image-renderer/pull/216
The default bash used in CircleCi is `/bin/bash -eo pipefail` and `-e` means:
> Exit immediately if a pipeline (which may consist of a single simple command), a subshell command enclosed in parentheses, or one of the commands executed as part of a command list enclosed by braces exits with a non-zero status.
As explained here: https://circleci.com/docs/2.0/configuration-reference/#default-shell-options

Chore: Don't fail PR build if plugin signing fails fix

---

package.json
scripts/download_chromium.js
src/app.ts
src/browser/browser.ts
yarn.lock

- Upgrade puppeteer, typescript and prettier to the latest versions
Tested on Mac and it builds and works ok. Could use more tests on other OS probably. 
Also did some brief profiling and it seems like total rendering time per panel is decreased by ~400ms, could be due to the newer versions of Chronium used.

Upgrade dependencies

---

yarn.lock

Although [we've discarded this as an actual security issue](https://raintank-corp.slack.com/archives/C011GT1NESU/p1628456647023400?thread_ts=1628181994.022700&cid=C011GT1NESU) because it's a 3rd party dependency of a development dependency, it's still making security scanners to complain. So, could be good idea to update it and stop those complaints.

Update path-parse to v1.0.7

---

default.json
dev.json
devenv/docker/ha/config.json
docs/remote_rendering_using_docker.md
src/browser/index.ts
src/config.ts

While doing some load testing of the application with the `default` rendering mode, I noticed high CPU and memory slowy going to the roof after the tests were finished. I narrowed down the issue to the `newPage` function that was (for some requests) hanging forever, preventing the browser to be closed and causing these issues. 
It seems like adding the `--disable-gpu` flag to the Chromium args fixed the issue.
Should fix https://github.com/grafana/grafana-image-renderer/issues/229

Add --disable-gpu in the default Chromium args

---

Dockerfile

Use the same working directory as before to not break existing Docker set-ups.
I'm no Docker expert so if there is a benefit to use `/usr/share/grafana` instead of `/usr/src/app`, we can keep it but if there isn't, then, it's best to not introduce a breaking change for Docker users.

Docker: revert changes on the working directory

---

default.json
devenv/docker/custom-config/config.json
src/config.ts

In the reporting configuration, we suggest to use `4` in the `image_scale_factor` field for printed materials. With the current defaults, it would be ignored and set to `1` as the default `maxDeviceScaleFactor` is `3`. This PR fixes that.

Set the maximum device scale factor to 4 as default

---

package.json
src/service/http-server.ts
src/service/metrics_middleware.ts

Add gauge of total number of requests in flight (only for `/render/*` routes). 
Closes https://github.com/grafana/grafana-image-renderer/issues/234

Instrumentation: Add gauge of total number of requests in flight

---

default.json
dev.json
devenv/docker/custom-config/config.json
devenv/docker/ha/config.json
src/app.ts
src/browser/clustered.ts
src/browser/index.ts
src/config.ts
src/plugin/v2/grpc_plugin.ts

Add timeout setting that overrides puppeteer-cluster timeout. 
Fixes https://github.com/grafana/grafana-image-renderer/issues/279

Configuration: add timeout setting for clustered mode

---

package.json
yarn.lock

Bump `pkg` from 5.3.3 to 5.4.1.
Not much to review here but I'd like to get the packages for MacOS and Linux tested before merging this (they are available in CircleCI).

Chore: bump pkg from 5.3.3 to 5.4.1

---

src/browser/browser.ts
src/browser/clustered.ts
src/browser/reusable.ts
src/plugin/v2/grpc_plugin.ts
src/service/http-server.ts
src/types.ts

There are currently two types `RenderOptions` and `RenderCSVOptions` however, CSV is just a subset of the other types.  In addition, the HTTP server has an identical type but it is called `RenderRequest`  -- grpc plugin has a similar type -- but headers is string[] rather than string so :man_shrugging: 
This PR:
1. adds a types.ts file to root and puts RenderOptions and ImageRenderOptions there
2. avoids using `any` in function calls
3. use the same options type for browser and server
This has no behavior changes

Types: improve options types

---

.circleci/config.yml
.gitignore
CHANGELOG.md
Makefile
default.json
dev.json
package.json
scripts/download_sharp.js
scripts/package_target.sh
scripts/pkg.js
src/app.ts
src/browser/browser.ts
src/config.ts
src/types.ts
yarn.lock

This PR updates the image renderer to support creating thumbnails from a requested page.  Rather than adding a new parameter, this is reusing the scale/deviceScaleFactor parameter and using negative numbers.
For the request:
http://localhost:3000/render/d/zNigXIonz/heatmap?kiosk&orgId=1&width=320&height=240&scale=-5
It will render an image a 320*5 and then scale it back down to 320px:

Previews: support creating thumbnails and full-height screenshots

---

src/browser/browser.ts

Fix old alert list panel rendering (before Grafana 8 and React migration) by setting the `captureBeyondViewport` screenshot option to false by default.

Set captureBeyondViewport to false by default

---

.circleci/config.yml

Alternative to https://github.com/grafana/grafana-image-renderer/pull/352 
I think this is better to use the `grafana` Docker image instead of an individual one that could be used to test things or be outdated.

CI: fix scan Docker image

---

package.json
yarn.lock

Bump jpeg-js from 0.4.2 to 0.4.4 to fix following vulnerability: CVE-2022-25851

Bump jpeg-js from 0.4.2 to 0.4.4

---

CHANGELOG.md
plugin.json

`prepare` step from https://github.com/grafana/grafana-image-renderer/blob/master/docs/release_new_version.md#prepare

Release grafana-image-renderer v3.5.0

---

src/service/http-server.ts

It uses `content-disposition` library to accept non-ascii characters in Content-Disposition header. Right now its failing when it's happening and we aren't creating the csv.
Related issue: https://github.com/grafana/grafana-enterprise/issues/3576

Fix invalid Content-Disposition

---

src/browser/browser.ts
src/service/http-server.ts

The condition that we are using for individual panels isn't working for full page screenshots.
`panelsRendered` value is increased every time a panel is rendered. But a panel could be renderer several times when scrolling. For example, when a panel is partially visible increases `panelsRendered`, and when scroll, it increases this value again. 
So `(window as any).panelsRendered >= panelCount` could be success even if we have any panel loading data. If we have a slow query, the result could be a screenshot with a loading panel, when we are expecting to see data.
The condition for full pages is the following:
* Count `[data-panelId]` as total panels of the dashboard (rendered or not). It includes rows and panels.
* `.dashboard-row` returns the number of rows.
* `.panel-content` returns the …

Update waiting condition for full page screenshots

---

.circleci/config.yml
Dockerfile
debian.Dockerfile
package.json
yarn.lock

- Sync dev dependency versions with Grafana and pin their exact versions
- Update Node to v 16

Chore: Update to Node 16

---

src/browser/browser.ts

It changes `_client` with `_client()` to make CSV works with last puppeteer update.
Fixes: https://github.com/grafana/grafana-image-renderer/issues

Update _client with _client() to avoid to fail when creating a CSV

---

src/browser/browser.ts

Errors related to `JSHandle@object` are showing like errors when in most of the cases is because it cannot load a `js` that doesn't affect to the screenshot. I didn't see this error in other other cases.
The result when image-renderer is used as plugin is that it's showing a lot of annoying messages on logs because they are errors, but down the log level to debug removes a lot of noisy.

Log errors related to JSHandle@object as debug

---

.circleci/config.yml

**What this PR does**:
It removes the `security_scan` job from PRs' pipelines.
**Why do we need it**:
It's causing issues to / conflicting with community pull requests (like [here](https://github.com/grafana/grafana-image-renderer/pull/387#issuecomment-1330445915)) while I don't think it's that critical to keep it there - actually I don't think we continuously analyze (on a pull request basis) the output of those security scans, so I think keeping them only on master builds is enough.
In fact, that's what we do with Grafana's repo, if I'm not wrong.
**Special notes for your reviewer**:

Stop doing security scans on PRs

---

README.md

Changed https://grafana.com/grafana/plugins/grafana-image-renderer into https://github.com/grafana/grafana-image-renderer/ where the git clone is referenced

Updated the clone url to point to the repository

---

src/browser/browser.ts

Related: https://github.com/grafana/support-escalations/issues/5010
Looks like that `req.failure()` could be null and it fails when it happens.

Fix error when req.failure() is null

---

package.json
yarn.lock

Bump jimp from 0.16.1 to 0.16.13 to fix following vulnerability: CVE-2022-36313

Bump jimp from 0.16.1 to 0.16.13

---

scripts/clean_target.sh
src/app.ts
src/config.ts
src/plugin/v2/grpc_plugin.ts
src/service/middlewares.ts

To rotate authentication tokens in a distributed environment, updating the renderer token means breaking the rendering features in Grafana until the Grafana instances are updated with the right token.
Allowing to set up an array of authentication tokens allows to rotate tokens without downtime. 
Notes:
- In environment variables, tokens can be set as space delimited strings (as tokens could contain commas).
- Still support setting the auth token as a string to not introduce a breaking change.

Security: can set array of auth tokens

---

Dockerfile

Adding alpine edge repo might cause dependencies to get unnecessarily bumped

remove alpine edge repo

---

README.md

This is a start, I don't know if this is what you had in mind when you wrote https://github.com/grafana/grafana-image-renderer/issues/388
Closes https://github.com/grafana/grafana-image-renderer/issues/388

Docs: add security section

---

src/browser/browser.ts

Fix the condition to wait for all panels to load when doing a full dashboard page screenshot.
The current condition is not working so the timeout is reached every time we do a dashboard screenshot.

Fix fullpage waitFor conditions

---

scripts/download_chrome.js
src/app.ts
src/plugin/v2/grpc_plugin.ts

The Puppeteer update (https://github.com/grafana/grafana-image-renderer/pull/433) contained an update to the `puppeteer.executablePath` function used in plugin mode to compute Chrome executable path. 
This PR updates the package scripts to ensure Chrome is always installed under `<pluginDir>/chrome` so we can use this path in plugin mode. 
Fixes https://github.com/grafana/grafana-image-renderer/issues/449

Plugin: fix Chrome path

---

scripts/publish_github_release.sh

When making a release, the changelog for the latest version is wrong (the changelog for the previous version is used). This PR should fix this.
Fixes https://github.com/grafana/grafana-image-renderer/issues/427

Chore: Fix release notes

---

src/app.ts
src/browser/browser.ts

This PR reverts a change from https://github.com/grafana/grafana-image-renderer/pull/433
The [new headless](https://developer.chrome.com/articles/new-headless/) mode for Chrome is known to have some issues including [one](https://github.com/puppeteer/puppeteer/issues/10829) that seems to make Chrome crash when using Kubernetes. 
As this prevents several Kubernetes users to upgrade their grafana-image-renderer, it's best to revert to the old headless mode until there is more information regarding the issues above.
Fixes https://github.com/grafana/grafana-image-renderer/issues/458 and https://github.com/grafana/grafana-image-renderer/issues/450

Browser: Revert to old headless mode

---

src/app.ts

The [`timezone` config](https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/#default-timezone) is not working since it's always being overwritten by env variables even if `env['TZ']` is unset/null. 
This fixes the issue to enable `timezone` config properly recognized by runtime

Fix issue of timezone config being always overwritten

---

.drone.yml
scripts/build_push_docker.sh
scripts/drone/common.star
scripts/drone/promotion.star

Switch all scripts execution to be executed with /bin/bash instead of sh. This fixes the [Drone current failure](https://drone.grafana.net/grafana/grafana-image-renderer/194/1/10) as the sh shell has no syntax to create arrays, but Bash has.

Drone: Fix push to Docker step

---

.drone.yml
scripts/build_push_docker.sh
scripts/drone/promotion.star

Based on https://github.com/grafana/grafana-image-renderer/pull/470
This PR upgrade the base image to build Docker images to be able to use `docker buildx`. Plus this creates a non-default Docker builder to be able to build for multiple platforms.

Drone: Fix docker buildx usage

---

README.md

The link toward Grafana documentation is currently broken, it brings to the generic documentation on Docker and not the one that describes how to build a custom image.

Doc: Update link to Grafana documentation

---

.drone.yml
scripts/drone/utils.star
scripts/drone/vault.star

In [my last PR](https://github.com/grafana/grafana-image-renderer/pull/479) to introduce tests for the image renderer, I forgot to run `make drone` at the end, so we were still using the non-officially released image `grafana/docker-puppeteer:pre-node-20`.
This PR replaces it with the published `us-docker.pkg.dev/grafanalabs-dev/grafana-ci/docker-puppeteer:2.0.0` image. The content is the same but it's the correct way to use the image and it will help us in the future if we release new versions of this image (as they won't be available on Docker).

Update image to run tests in CI

---

src/browser/browser.ts

This improves and simplifies the waiting for panel queries and panel rendering logic. 
Instead of scanning for how many panels there are using css selectors and comparing this to panel content (which is a bit unreliable / fragile) we just wait for all network requests to be completed and then an additional 100ms for data rendering (this step should be blocking so maybe we can lower this).

WaitingForPanels: Change waiting logic

---

src/browser/browser.ts

When we wanted to zoom in on the PDF, the resolution was bad because we printed with a scale > 100%.
This viewport zoom fixes this.

PDF: Fix resolution when zooming in

---

.drone.yml
package.json
scripts/drone/pipeline.star
scripts/drone/promotion.star

I tested it without the token to not publish wrong data and the command got executed here: https://drone.grafana.net/grafana/grafana-image-renderer/333/1/13 (but failed because of the token).

CI: Fix publish to gcom step

---

.drone.yml
scripts/drone/pipeline.star
scripts/drone/promotion.star

Since Alpine released its latest version (3.19.x), the Linux plugin that runs with `glibc` has not been working anymore. To fix this, we should replace `glibc` with `gcompat`, but this could break support for other plugins. Hence, this seems better to release a new package.
This can't replace the Linux package because it doesn't work on Linux distributions that don't work with `musl` (tested on OpenSUSE and it's not working, I guess it would be the same on RHEL). 
Part of fixing https://github.com/grafana/grafana-image-renderer/issues/505 (Once this PR is merged, this should be updated to use it: https://github.com/grafana/grafana/blob/main/packaging/docker/custom/Dockerfile#L37)
Another solution could be to switch the Grafana image used in the [custom …

Packages: Release Alpine package without Chromium

---

default.json
src/service/config.ts
src/service/http-server.ts

Add HTTPS configuration field to start the image renderer as an HTTPS server. 
Fixes https://github.com/grafana/grafana-image-renderer/issues/485
Doc PR: https://github.com/grafana/grafana/pull/88505

Server: Support HTTPS configuration

---

yarn.lock

Replace https://github.com/grafana/grafana-image-renderer/pull/529 as it's breaking automated testing.

Chore: Upgrade chokidar and jest dependencies

---

src/service/http-server.ts

I refactored my code a bit at the end of my work on adding HTTPS support https://github.com/grafana/grafana-image-renderer/pull/527 breaking the behavior when `host` is not defined. This fixes it.

HTTPS: Fix creation when host is not defined

---

src/browser/browser.ts

On non-scenes dashboards when `bodyScrolling` is enabled, we need to scroll the window.
Fixes https://github.com/grafana/grafana-enterprise/issues/6938

Scroll correct element when `bodyScrolling` is enabled

---

src/browser/browser.ts

This PR fixes blank page screenshot bug.
Puppeter resizes the viewport when taking a screenshot. See details [here](https://stackoverflow.com/questions/68059664/puppeteer-page-screenshot-resizes-viewport)
After [this PR](https://github.com/grafana/grafana/pull/90755) in scenes, when taking the screenshot `isMobile` is true for a while (randomly). That makes the dashboard re-render and the screenshot ends up being a blank page, showing only the NavToolbar.
[Issue thread](https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1722456214228329).
With `captureBeyondViewport` as false, it works as expected, because we set the viewport based on [panels container `scrollHeight`](https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts#L211) …

Full page image: Fix blank page 

---

package.json
yarn.lock

This PR upgrades poolpeteer to fix the usage of the `contextPerRenderKey` mode with the Puppeteer upgrade.

Deps: Upgrade poolpeteer

---

.drone.yml
scripts/drone/vault.star

Update the path to manage inside the team if needed. This will soon be deprecated in favor of the GitHub App.

Chore: Update ci token path

---

CHANGELOG.md
plugin.json

- Support cancel rendering requests on client cancellation [#588](https://github.com/grafana/grafana-image-renderer/pull/588), [AgnesToulet](https://github.com/AgnesToulet)
- Chore: Add ENV variables for temp folders in Docker [#583](https://github.com/grafana/grafana-image-renderer/pull/583), [evictorero](https://github.com/evictorero)
- Add image source label to dockerfiles [#573](https://github.com/grafana/grafana-image-renderer/pull/573), [wuast94](https://github.com/wuast94)

Release 3.12.0

---

src/service/metrics.ts

Currently, the endpoint /render/version is included in the following metrics:
- grafana_image_renderer_service_http_request_duration_seconds
- grafana_image_renderer_http_request_in_flight
This doesn't really make sense as we want to track the duration of rendering requests. Plus, they don't have at all the same duration (a rendering requests takes several seconds to be completed while /render/version takes a hundred milliseconds).

Metrics: Exclude /render/version from duration and inflight metrics

---

CHANGELOG.md
plugin.json

- Chore: upgrade deps [#593](https://github.com/grafana/grafana-image-renderer/pull/593), [AgnesToulet](https://github.com/AgnesToulet)
- Logs: Redirect log in response [#589](https://github.com/grafana/grafana-image-renderer/pull/589), [juanicabanas](https://github.com/juanicabanas)
- Metrics: Exclude /render/version from duration and inflight metrics [#591](https://github.com/grafana/grafana-image-renderer/pull/591), [AgnesToulet](https://github.com/AgnesToulet)

Release 3.12.1

---

src/service/config.ts

Add support to configure HTTPS (added in [this PR](https://github.com/grafana/grafana-image-renderer/pull/527)) using environment variables
Fixes: https://github.com/grafana/grafana-image-renderer/issues/536

Server: Support HTTPS configuration using env variables

---

default.json
dev.json
devenv/docker/custom-config/config.json
src/app.ts
src/browser/browser.test.ts
src/browser/browser.ts
src/browser/reusable.ts
src/config/config.ts
src/config/rendering.ts
src/plugin/v2/grpc_plugin.ts
src/service/config.ts
src/service/http-server.integration.test.ts
src/service/http-server.ts
src/tracing.ts

This PR adds tracing to the plugin mode and update a few things from the original PR:
- Read the config file before initializing tracing, this allows to have the exporter URL set in the config file instead of using an env variable
- Do no intialize the `tracer` variable if tracing is disabled
- Propagate the trace context back to Grafana
**What remains:**
**To test the plugin on Mac:**
1. Build the plugin locally for Mac:
1. Update your `Makefile` to set `ARCH = darwin-arm64-unknown` 
1. Run `make build_package`
1. The plugin will be built in the `dist` folder
2. Copy / paste the built plugin to your Grafana plugins folder and rename it to `grafana-image-renderer`
3. In your Grafana .ini file:
1. Comment your remote renderer settings in the `[rendering]` section
2. Add the following …

Add tracing to plugin mode and improve config management

---

CHANGELOG.md
plugin.json

- Image Render: Support Tracing [#586](https://github.com/grafana/grafana-image-renderer/pull/586), [lucychen-grafana](https://github.com/lucychen-grafana)
- Server: Support HTTPS configuration using env variables [#600](https://github.com/grafana/grafana-image-renderer/pull/600), [evictorero](https://github.com/evictorero)
- Docs: Update run server options [#599](https://github.com/grafana/grafana-image-renderer/pull/599), [evictorero](https://github.com/evictorero)
- Chore: Upgrade to Node 22 [#595](https://github.com/grafana/grafana-image-renderer/pull/595), [AgnesToulet](https://github.com/AgnesToulet)

Release 3.12.2

---

CHANGELOG.md
plugin.json

- Revert "Image Render: Support Tracing (#586)" [#609](https://github.com/grafana/grafana-image-renderer/pull/609), [lucychen-grafana](https://github.com/lucychen-grafana)

Release 3.12.3

---

Dockerfile
package.json
src/sanitizer/Sanitizer.ts
yarn.lock

[CVE Dashboard](https://ops.grafana-ops.net/a/grafana-vulnerabilityobs-app/projects/sources/6/version/14256?var-package=&var-cve=&var-riskLevel=$__all&var-pkg=) 
Bump dompurify 2.5.4 to 3.2.4 [CVE-2025-26791](https://avd.aquasec.com/nvd/2025/cve-2025-26791/)
libxslt [CVE-2025-24855](https://avd.aquasec.com/nvd/2025/cve-2025-24855/) [CVE-2024-55549](https://avd.aquasec.com/nvd/2024/cve-2024-55549/), libexpat [CVE-2024-8176](https://avd.aquasec.com/nvd/2024/cve-2024-8176/), and libjxl [CVE-2024-11403](https://avd.aquasec.com/nvd/2024/cve-2024-11403/) will be updated in Chromium

Chore: Update dompurify to fix CVE

---

CHANGELOG.md
plugin.json

Release 3.12.4
- Chore: Update dompurify to fix CVE [#614](https://github.com/grafana/grafana-image-renderer/pull/614), [lucychen-grafana](https://github.com/lucychen-grafana)
- Chore: Downgrade to Node 20 [#619](https://github.com/grafana/grafana-image-renderer/pull/619), [evictorero](https://github.com/evictorero)

Release 3.12.4

---

src/browser/browser.ts

The `.pdf` function currently uses the default timeout (30s) instead of the provided timeout as every other function during the rendering process.
When printing a PDF for a very large dashboard, this leads to not being able to customize the timeout.

PDF: Use sent timeout

---

CHANGELOG.md
plugin.json

- PDF: Use sent timeout [#628](https://github.com/grafana/grafana-image-renderer/pull/628), [AgnesToulet](https://github.com/AgnesToulet)
- Docker: Remove unused NPM files [#625](https://github.com/grafana/grafana-image-renderer/pull/625), [AgnesToulet](https://github.com/AgnesToulet)
- Docker: Add chromium-swiftshader to support webGL [#623](https://github.com/grafana/grafana-image-renderer/pull/623), [AgnesToulet](https://github.com/AgnesToulet)

Release 3.12.5

---

default.json
dev.json
devenv/docker/ratelimiter/config.json
devenv/docker/ratelimiter/docker-compose.yaml
package.json
src/service/config.ts
src/service/http-server.integration.test.ts
src/service/http-server.ts
src/service/middlewares.ts
src/service/ratelimiter.ts
yarn.lock

This PR adds a rate limiter to the server mode of the image renderer.
WIP, what remains:
Depends on https://github.com/grafana/grafana/pull/103987
Fixes https://github.com/grafana/grafana-enterprise/issues/7794

Server: Add rate limiter

---

.drone.yml
scripts/drone/promotion.star
scripts/drone/vault.star

Current Docker secrets defined in Drone are no longer working. Moving to using secrets in Vault.

CI: Fix Docker secrets

---

src/browser/browser.ts
src/browser/clustered.ts
src/browser/reusable.ts

It seems that `page.on('request', ...)` isn't triggered on EVERY request so adding the headers for every request and removing them here wasn't working for some requests.
This is achieving the same result, the other way around, only adding headers for requests we are sure we should add them.

Tracing: Fix tracing headers causing CORS issue

---

CHANGELOG.md
plugin.json

- Chore: Upgrade multer 2.0.0 [#642](https://github.com/grafana/grafana-image-renderer/pull/642), [evictorero](https://github.com/evictorero)
- Tracing: Fix tracing headers causing CORS issue [#640](https://github.com/grafana/grafana-image-renderer/pull/640), [AgnesToulet](https://github.com/AgnesToulet)
- Tracing: improve logs [#639](https://github.com/grafana/grafana-image-renderer/pull/639), [AgnesToulet](https://github.com/AgnesToulet)
- Image Render: Support tracing [#612](https://github.com/grafana/grafana-image-renderer/pull/612), [lucychen-grafana](https://github.com/lucychen-grafana)
- CI: Fix Docker secrets [#636](https://github.com/grafana/grafana-image-renderer/pull/636), [AgnesToulet](https://github.com/AgnesToulet)
- Server: Add rate limiter …

Release 3.12.6

---

CHANGELOG.md
plugin.json

Bumps the base `node:20-alpine` image to latest to trigger a new release.

Chore: Update base Docker image to latest

---

.github/CODEOWNERS
Dockerfile

Grafana Enterprise now owns the repository.
Also updating the Dockerfile to point to the right file, so as to hopefully fix Grafana VulnO11y's ownership attribution.

Codeowners: Update ownership

---

package.json
yarn.lock

[CVE SLO ](https://ops.grafana-ops.net/a/grafana-vulnerabilityobs-app/projects/sources/20/version/23131?var-cve=&var-pkg=)
Bumps [multer](https://github.com/expressjs/multer) from 2.0.0 to ^2.0.1.
[CVE-2025-48997](https://ops.grafana-ops.net/a/grafana-vulnerabilityobs-app/cves/details/CVE-2025-48997)
Bumps tar-fs from 3.0.8 to ^3.0.9
[CVE-2025-48387](https://ops.grafana-ops.net/a/grafana-vulnerabilityobs-app/cves/details/CVE-2025-48387)

Bump CVE multer and tar-fs

---

CHANGELOG.md
Dockerfile
plugin.json

We need to rebuild the Docker image again, as Chromium has updated.
To ensure we can trust we have AT LEAST the version we want, I've also added the version constraint into the Dockerfile. It isn't reproducible, as it is NOT a pin, but it does verify we have the minimum fixed version.
Fixes: CVE-2025-6191
Fixes: CVE-2025-6192

Docker: Update base Docker image

---

Dockerfile

Chromium released 138.0.7204.93. Let's update to it.

Docker: Update Chromium in alpine

---

devenv/docker/custom-config/docker-compose.yaml
devenv/docker/simple/docker-compose.yaml
devenv/loadtest/README.md
devenv/loadtest/modules/client.js
devenv/loadtest/render_test.js
devenv/loadtest/run.sh

This PR fixes and improves our load tests:
- Fix login workflow
- Add support for service account token
- Use new k6 Docker image
+ some clean up in Docker files (as the version is no longer used and generate a warning)

Load tests: Improve scripts

---

.github/workflows/build-plugin.yaml
CHANGELOG.md
docs/release_new_version.md
plugin.json

I had forgotten that the `upload-artifacts` action will only not keep parent dirs if all files are in the same place 🙄

Actions: Upload correct md5sums.txt path

---

CHANGELOG.md
Dockerfile
plugin.json

Kubernetes requires this if users configure the service to run with non-root users.
Fixes: https://github.com/grafana/grafana-image-renderer/issues/686

Docker: Use numeric UID

---

tests/bats/chromium-exists.bats
tests/bats/docker.bash
tests/bats/regression-676.bats
tests/bats/regression-680.bats
tests/bats/regression-686.bats
tests/bats/regression-694.bats
tests/bats/service-starts.bats

This will now keep test containers around long enough to print their logs. We'll still clean them up after the test ends like usual, on both test failure and success.
If you now fail a test, it'll print the logs, e.g.:
```
regression-694.bats
✗ openshift: docker image starts with random UID
(from function `_wait_for_healthy' in file tests/bats/docker.bash, line 64,
in test file tests/bats/regression-694.bats, line 23)
`_wait_for_healthy "$output"' failed
error: container 7efd53ae0664926976cf6ee2c3c5915eaa634ae42e10d57c6d7d47cc0eff73a3 is not running
node:internal/modules/cjs/loader:1404
throw err;
^
Error: Cannot find module '/home/nonroot/build/app.js'
at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19) …
```

Tests: Keep containers around to print logs

---

renovate.json

Opt out of all other default feature presets for renovate except dockerfile ([reference](https://github.com/grafana/grafana-renovate-config/blob/main/README.md#opting-out-of-presets))
Will not automerge yet, need to confirm everything works first

Renovate: Configure for Dockerfile only

---

renovate.json

Disables `npm` updates, since the PRs that renovate creates are noisy and broken.

feat(renovate): explicitly disable npm updates

---

src/browser/browser.ts
src/service/http-server.ts
src/types.ts

If the `XDG_CACHE_HOME` and/or `XDG_CONFIG_HOME` env vars are not set, we create a temp dir per requests to protect tenant boundary and delete it up when the request finishes.
Fixes https://github.com/grafana/grafana-image-renderer/issues/748
It was noted that in some Linux environments such as OpenShift, the lack of those environment variables caused a crash in Chromium when attempting to render:
```
Otherwise errors like this one would happen:
Error: Failed to launch the browser process!
chrome_crashpad_handler: --database is required
```

HTTPServer: Dynamically create and clean up XDG dirs on each request if not exists

---

README.md

For a little while longer, we will still provide updates and fixes to the plugin mode, however it will not last (i.e. we won't support it at all in 5.0.0).
This puts up a deprecation warning, such that it is clear that you should not use the plugin mode.
**Grafana Employee?** See [our design doc here](https://docs.google.com/document/d/1qm2AM1mf0z4ju6mkWlHmT6GEZ41VQ8axTEsGqfj5-Xo/edit?usp=sharing).

docs: deprecation warning for the plugin

---

pkg/service/browser.go

We keep having flaky tests, showing that general server CPUs (which have lower single- & few-core performance than the CPU I use to develop) generally do not perform well enough with Chromium. This manifests for us in flaky tests, and would in practice also result in poor results for customers' reports.
In order to battle this, we'll stop waiting for each stabilisation step in order, to requiring them all to be true at once. This also adds more steps: we will now wait for queries, network requests, AND the HTML DOM to stabilise.
This does not solve the problem fully -- it is not possible to properly, fully solve. We have to strike a balance in finding "the right time" to do a print; this is the entire problem, and we've been too eager to print up until this change.

feat(go): let multiple stabilisation steps share reruns

---

.github/workflows/docker-scan.yaml
.github/workflows/docker-test.yaml
.github/workflows/docker.yaml

Our docker builds are relatively slow, so using our own runners with faster CPUs helps. Wherever we replace larger-than-default GH runners, we also save money.

ci: use self-hosted runners for Docker

---

pkg/service/browser.go

CORS headers ensure that we cannot always send `traceparent` via the browser, according to the browser. However, we want to always send the header regardless of CORS, such that the receiving service can decide whether it wants to care about it.
As such, we should use the `Fetch` APIs, which let us arbitrarily change the outgoing requests without any CORS restrictions.
Thanks to Josh for helping me figure this out!

fix(go): propagate traceparent without respecting CORS
