grafana/grafana-image-renderer

- .circleci/config.yml
- Makefile
- scripts/archive_target.sh
- scripts/clean_target.sh
- scripts/download_chromium.js
- scripts/download_grpc.js
- scripts/package_target.sh
- scripts/pkg.js
- scripts/rename_executable.js
- src/app.ts
- src/browser.ts
- src/grpc-plugin.ts
- src/http-server.ts
- src/logger.ts
Support building without packaging chromium.
Build linux-x64-glibc artifact without chromium in ci
> Build: Support build/package without chromium

- package.json
- yarn.lock
Somehow having `"private": true` in package.json made puppeteer fail when running as plugin. Not when running in docker. Super weird!
> Make plugin work again

- default.json
- dev.json
- docs/remote_rendering_using_docker.md
- package.json
- src/app.ts
- src/browser/browser.ts
- src/browser/clustered.ts
- src/browser/reusable.ts
- src/config.ts
- src/logger.ts
- src/plugin/grpc-plugin.ts
- src/service/http-server.ts
- yarn.lock
Improves debugging and logging. 
Subscribing to page events to catch errors from browser 
when rendering image.
Possible to adjust log level using `LOG_LEVEL` 
environment variable when running as service.
Possible to adjust console logging by configuration 
file when running as service.
Closes #85
> Improve debugging and logging

- package.json
- yarn.lock
Seems like v4.4.2 of pkg broke the build for Windows.
Fixes #102
> Plugin: Pin pkg to v4.3.8

- package.json
- yarn.lock
https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
> Use minimist v1.2.5 due to security report

- proto/pluginv2.proto
/api/plugins/grafana-image-renderer/health now works again.
> Sync latest changes of pluginv2 proto

- README.md
Removes IPv6 known issue.
Removes environment variables.
Adds configuration section.
Closes #130
> Docs: v2.0.0 update

- README.md
Fix troubleshooting link in README.
> README: Fix troubleshooting link

- .circleci/config.yml
Fixes #215 
Not sure this would work. A bit tricky to test.
> Chore: Don't fail PR build if plugin signing fails

- scripts/package_target.sh
Add CHANGELOG.md in the package files so it can be read and displayed by grafana.com (https://grafana.com/grafana/plugins/grafana-image-renderer/?tab=changelog).
> Chore: add changelog in package

- Dockerfile
- debian.Dockerfile
Fixes #247 
Signed-off-by: Matt Bentley <mbentley@mbentley.net>
> Add plugin.json to the renderer Docker images

- mixin/.gitignore
- mixin/Makefile
- mixin/README.md
- mixin/alerts/alerts.yaml
- mixin/dashboards/image-render-service.json
- mixin/mixin.libsonnet
- mixin/rules/rules.yaml
- mixin/scripts/build.sh
- mixin/scripts/common.sh
- mixin/scripts/format.sh
- mixin/scripts/lint.sh
A bundle of alerts, recording rules, and dashboards that we can deploy to our production services. 
Once merged we can include them in our cloud monitoring stack. 
Signed-off-by: bergquist <carl.bergquist@gmail.com>
> Monitoring mixin 

- .circleci/config.yml
- scripts/build_push_docker.sh
Signed-off-by: bergquist <carl.bergquist@gmail.com>
> Push docker image for the master branch

- src/browser/browser.ts
It updates some deprecated functions to the new ones.
> Update deprecated functions

- default.json
- src/app.ts
- src/browser/browser.ts
- src/config.ts
- src/plugin/v2/grpc_plugin.ts
Fixes #385
Added option for page zoom level. Allows dashboards to be zoomed (for bigger titles, etc.)
> Added page zooming option

- yarn.lock
Tested in plugin mode on Windows and in remote server mode.
> Chore: update all dependencies

- scripts/build_push_docker.sh
> Build for arm64

- package.json
- yarn.lock
Upgrade Jimp deps to fix GHSA-x565-32qp-m3vf
> Chore: Upgrade Jimp deps

- package.json
- yarn.lock
Upgrade deps to keep up-to-date packages.
Tested it on Ubuntu in plugin mode and remote mode.
> Chore: upgrade deps

- README.md
Fixes: https://github.com/grafana/grafana-image-renderer/issues/494
> Docs: Update run server options

- .github/workflows/snyk.yml
Fix findings reported by https://github.com/woodruffw/zizmor
> CI: improve workflow security

- .dockerignore
- .github/workflows/docker-test.yaml
- tests/bats/docker.bash
- tests/bats/service-starts.bats
This should solve our problems with failing tests.
> Tests: Fix bats tests

- .gitignore
- cmd/server/cmd.go
- devenv/docker/enterprise-host/docker-compose.yaml
- pkg/api/mux.go
- pkg/api/render.go
- pkg/api/version.go
- pkg/chromium/browser.go
- pkg/version/service.go
This extends the rendering support to work for Grafana dashboards.
> feat(go): support rendering Grafana dashboards

- go.mod
- go.sum
- pkg/api/healthz_test.go
- pkg/api/middleware/metrics_test.go
- pkg/api/middleware/recovery_test.go
- pkg/api/version_test.go
- tests/bats/service-fails-expectedly.bats
This extends our current test suite to more contract and unit tests. The unit tests are Go-specific, and contract tests apply to both implementations.
> test: add more unit and contract tests

- .github/workflows/build-plugin.yaml
Zizmor keeps complaining about this. Let's deal with it :)
> fix(ci): prevent cache poisoning
